### ISSUE TITLE
[REVIEW] JOSS review general discussion.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#87]
Please briefly describe your problem and what output you expect.

Please include a minimal reproducible example (AKA a reprex - View [documentation](http://reprex.tidyverse.org/) about reprexes).

---

## Brief description of the problem

```r
# insert reprex here
```

## Session Information

```console
# Insert Session info here
```

**Comment by grabear** [comment]
@lpantano @CosteaPaul @sdhutchins I created this Issue for general discussion about the JOSS review.  If you have any questions about the paper https://github.com/openjournals/joss-reviews/issues/1299

**Comment by grabear** [comment]
@CosteaPaul @lpantano Just checking in on this review.  How are things going?

**Comment by lpantano** [comment]
Hi @grabear 

I was giving some time to @CosteaPaul, I will ping him needed later.

Thanks!

**Comment by CosteaPaul** [comment]
The usage of "ordination_plot" describes the argument "distance" as:

distance: Choose a distance method from 'bray', 'unifrac' or 'wunifrac', Default: 'wunifrac'

However, because it's actually just forwarding a call to phyloseq::ordinate (which i guess is then just calling vegan), it is able to accept: "manhattan", "euclidean", "canberra", "bray", "kulczynski", "jaccard", "gower", "altGower", "morisita", "horn", "mountford", "raup", "binomial", "chao".

Don't even know how to go about quantifying how often this occurs, but this distance thing happens to be a pet peeve of mine which i why i specifically looked at it.

**Comment by sdhutchins** [comment]
@CosteaPaul Thanks! We can update this in the documentation and better explain. I think initially we weren't using phyloseq (maybe metacoder) and just had a mental lapse in the docs.

**Comment by sdhutchins** [comment]
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01299/status.svg)](https://doi.org/10.21105/joss.01299)

**Comment by sdhutchins** [comment]
Can be closed now.
